server:
  cli_main:
    debug: false
    gc_limit_mb: 512
    gc_percent: 30
    port: 9422
    keys:
      - name: 1
        public_key: "BNlt+QZ0StVPUuVlY5SLEijB0J51PvtMYK/F3Nd4HSs7khBFQhvyUosm/DG1mmspYiOS0Zd/yCFd4uyWQR7YWEI="
        private_key: "x97SIkFTlNUpTsNAdsHURjFQZ3BLL/iQ8bBW+hHV7mk="
      - name: 2
        public_key: "BL9HfxXeg9+L0vR24xFbMHw8XIUzhKFouFvVQ6T9bbEvzrS0i9fhNTzPYALSzRUZBF//8a3BSb0yu9NurwLqz6k="
        private_key: "bsnBl3aP0hrgpwp6oqA5Dr87VWwfM8xJ/6jy9NBkVVo="
      - name: 3 # 业务系统 - CLI交互
        public_key: "BBmbUczNP4LcmA8hQv7JRhFOtuy3cXfHEx/0En3Tys76vnWxmz94nGEi+Yq8U6NFNU/T9TB7AAjIJ7PdA94ShRc=" # 8xBOZ2lJFjssqzC13rq/LuMUtdZX3I4K4uHM5V7UVaU=
        private_key: "yRR2MArJezOUUo9jV5AIo9g96hiFYlpp+Rd6I2i/2O0=" # BIc/kRgCbH/sSX3yVi7fCjoDBYyO99NzC6lJj/c16e5wcZzDT9OEDzEEff9dniAvMP/4LKuB/4R9XRtLHSAS8Bs=


jwt:
  cli_main:
    token_key: "7798959a278acb81e35d798fcc38329cfdc80a84db89a5eb471ec5c671e78b6f"
    token_alg: "HS256"
    token_typ: "JWT"
    token_exp: 1209600 # 两周，单位秒

logger:
  master:
    layout: 0
    location: "Asia/Shanghai"
    level: "error"
    console: false
    file_config:
      max_size: 50
      max_backups: 10
      max_age: 7
      compress: false

# 扩展参数
extract:
  appID: "e6a06259193fb8476ffd83a87c4fc300"
  appKey: "43cb8a4f8c795c74426aed363aa9c12af0d065ca33b472c6ec7ce5cf7bc47c7c"
  walletDir: "openwsdk/keys"
  walletMode: 3 # 钱包模式,1,3,5模式, 1=本地创建密码钱包 3,5进行分片管理（需要部署多个分片节点）
  remoteWhitelist: # 业务系统请求IP白名单
    - "127.0.0.1"
  signerWhitelist: # 交易JSON签名请求IP白名单
    - "127.0.0.1"
  nodeWhitelist: # 节点IP白名单
    - "127.0.0.1"
  signerBlacklist: # 签名黑名单地址，拒绝签名
    - "0xdAb9c307B8B23A8fD8559f75C71F0694Da30D9F6"
  summaryWhitelist: # 汇总白名单地址
    - "0xdAb9c307B8B23A8fD8559f75C71F0694Da30D9F6"
