// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(in *jlexer.Lexer, out *CliWalletResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(out *jwriter.Writer, in CliWalletResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int(int(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliWalletResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliWalletResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliWalletResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliWalletResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(in *jlexer.Lexer, out *CliUnlockWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(out *jwriter.Writer, in CliUnlockWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliUnlockWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliUnlockWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliUnlockWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliUnlockWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto1(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(in *jlexer.Lexer, out *CliUnlockWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "filename":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Filename = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(out *jwriter.Writer, in CliUnlockWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"filename\":"
		out.RawString(prefix[1:])
		out.String(string(in.Filename))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliUnlockWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliUnlockWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliUnlockWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliUnlockWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto2(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(in *jlexer.Lexer, out *CliSignTransactionRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.SignerList)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(out *jwriter.Writer, in CliSignTransactionRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix[1:])
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.SignerList {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliSignTransactionRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliSignTransactionRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliSignTransactionRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliSignTransactionRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto3(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(in *jlexer.Lexer, out *CliSignTransactionReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "tradeSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradeSign = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(out *jwriter.Writer, in CliSignTransactionReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix[1:])
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"tradeSign\":"
		out.RawString(prefix)
		out.String(string(in.TradeSign))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliSignTransactionReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliSignTransactionReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliSignTransactionReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliSignTransactionReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto4(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(in *jlexer.Lexer, out *CliFindWalletListRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]WalletResult, 0, 0)
					} else {
						out.Result = []WalletResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v3 WalletResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(out *jwriter.Writer, in CliFindWalletListRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Result {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliFindWalletListRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliFindWalletListRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliFindWalletListRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliFindWalletListRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto5(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(in *jlexer.Lexer, out *CliFindWalletListReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(out *jwriter.Writer, in CliFindWalletListReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliFindWalletListReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliFindWalletListReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliFindWalletListReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliFindWalletListReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto6(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(in *jlexer.Lexer, out *CliCreateWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(out *jwriter.Writer, in CliCreateWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto7(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(in *jlexer.Lexer, out *CliCreateWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(out *jwriter.Writer, in CliCreateWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto8(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(in *jlexer.Lexer, out *CliCreateAccountRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "otherOwnerKeys":
			if in.IsNull() {
				in.Skip()
				out.OtherOwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OtherOwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OtherOwnerKeys = make([]string, 0, 4)
					} else {
						out.OtherOwnerKeys = []string{}
					}
				} else {
					out.OtherOwnerKeys = (out.OtherOwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					out.OtherOwnerKeys = append(out.OtherOwnerKeys, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = int64(in.Int64())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(out *jwriter.Writer, in CliCreateAccountRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"otherOwnerKeys\":"
		out.RawString(prefix)
		if in.OtherOwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.OtherOwnerKeys {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReqSigs))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAccountRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAccountRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAccountRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAccountRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto9(l, v)
}
func easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(in *jlexer.Lexer, out *CliCreateAccountReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "lastIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastIndex = int64(in.Int64())
			}
		case "curve":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Curve = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(out *jwriter.Writer, in CliCreateAccountReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"lastIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastIndex))
	}
	{
		const prefix string = ",\"curve\":"
		out.RawString(prefix)
		out.Int64(int64(in.Curve))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CliCreateAccountReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CliCreateAccountReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC5d09f7cEncodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CliCreateAccountReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CliCreateAccountReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC5d09f7cDecodeGithubComBlocktreeGoOpenwSdkV2OpenwsdkDto10(l, v)
}
