// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto(in *jlexer.Lexer, out *GetContractsRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]ContractResult, 0, 0)
					} else {
						out.Result = []ContractResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 ContractResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto(out *jwriter.Writer, in GetContractsRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractsRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractsRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractsRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractsRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto(l, v)
}
func easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto1(in *jlexer.Lexer, out *GetContractsReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "sort":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sort = int(in.Int())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto1(out *jwriter.Writer, in GetContractsReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix)
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"sort\":"
		out.RawString(prefix)
		out.Int(int(in.Sort))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetContractsReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetContractsReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetContractsReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetContractsReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto1(l, v)
}
func easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto2(in *jlexer.Lexer, out *ContractResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "ctime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ctime = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto2(out *jwriter.Writer, in ContractResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix)
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"ctime\":"
		out.RawString(prefix)
		out.Int64(int64(in.Ctime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ContractResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ContractResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComOpenserverOpenStdrpcApiMainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ContractResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ContractResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComOpenserverOpenStdrpcApiMainDto2(l, v)
}
