// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFc450ad2DecodeGithubComOpenserverOpenStdrpcApiMainDto(in *jlexer.Lexer, out *CreateSubscribeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subscribeMethod":
			if in.IsNull() {
				in.Skip()
				out.SubscribeMethod = nil
			} else {
				in.Delim('[')
				if out.SubscribeMethod == nil {
					if !in.IsDelim(']') {
						out.SubscribeMethod = make([]string, 0, 4)
					} else {
						out.SubscribeMethod = []string{}
					}
				} else {
					out.SubscribeMethod = (out.SubscribeMethod)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.SubscribeMethod = append(out.SubscribeMethod, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "subscribeContract":
			if in.IsNull() {
				in.Skip()
				out.SubscribeContract = nil
			} else {
				in.Delim('[')
				if out.SubscribeContract == nil {
					if !in.IsDelim(']') {
						out.SubscribeContract = make([]string, 0, 4)
					} else {
						out.SubscribeContract = []string{}
					}
				} else {
					out.SubscribeContract = (out.SubscribeContract)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.SubscribeContract = append(out.SubscribeContract, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc450ad2EncodeGithubComOpenserverOpenStdrpcApiMainDto(out *jwriter.Writer, in CreateSubscribeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subscribeMethod\":"
		out.RawString(prefix[1:])
		if in.SubscribeMethod == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.SubscribeMethod {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"subscribeContract\":"
		out.RawString(prefix)
		if in.SubscribeContract == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.SubscribeContract {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSubscribeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc450ad2EncodeGithubComOpenserverOpenStdrpcApiMainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSubscribeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc450ad2EncodeGithubComOpenserverOpenStdrpcApiMainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSubscribeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc450ad2DecodeGithubComOpenserverOpenStdrpcApiMainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSubscribeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc450ad2DecodeGithubComOpenserverOpenStdrpcApiMainDto(l, v)
}
