// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto(in *jlexer.Lexer, out *SymbolResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "maxHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxHeight = int64(in.Int64())
			}
		case "curve":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Curve = int64(in.Int64())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int64(in.Int64())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "balanceMode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BalanceMode = int64(in.Int64())
			}
		case "icon":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Icon = string(in.String())
			}
		case "supportMemo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SupportMemo = int64(in.Int64())
			}
		case "onlyContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OnlyContract = int64(in.Int64())
			}
		case "withdrawStop":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WithdrawStop = int64(in.Int64())
			}
		case "blockStop":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockStop = int64(in.Int64())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "hash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hash = string(in.String())
			}
		case "merkleroot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Merkleroot = string(in.String())
			}
		case "previousblockhash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Previousblockhash = string(in.String())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = int64(in.Int64())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int64(in.Int64())
			}
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "fork":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fork = bool(in.Bool())
			}
		case "confirmations":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirmations = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto(out *jwriter.Writer, in SymbolResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"maxHeight\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.MaxHeight))
	}
	{
		const prefix string = ",\"curve\":"
		out.RawString(prefix)
		out.Int64(int64(in.Curve))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int64(int64(in.Decimals))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"balanceMode\":"
		out.RawString(prefix)
		out.Int64(int64(in.BalanceMode))
	}
	{
		const prefix string = ",\"icon\":"
		out.RawString(prefix)
		out.String(string(in.Icon))
	}
	{
		const prefix string = ",\"supportMemo\":"
		out.RawString(prefix)
		out.Int64(int64(in.SupportMemo))
	}
	{
		const prefix string = ",\"onlyContract\":"
		out.RawString(prefix)
		out.Int64(int64(in.OnlyContract))
	}
	{
		const prefix string = ",\"withdrawStop\":"
		out.RawString(prefix)
		out.Int64(int64(in.WithdrawStop))
	}
	{
		const prefix string = ",\"blockStop\":"
		out.RawString(prefix)
		out.Int64(int64(in.BlockStop))
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix)
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"merkleroot\":"
		out.RawString(prefix)
		out.String(string(in.Merkleroot))
	}
	{
		const prefix string = ",\"previousblockhash\":"
		out.RawString(prefix)
		out.String(string(in.Previousblockhash))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Int64(int64(in.Height))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int64(int64(in.Version))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"fork\":"
		out.RawString(prefix)
		out.Bool(bool(in.Fork))
	}
	{
		const prefix string = ",\"confirmations\":"
		out.RawString(prefix)
		out.String(string(in.Confirmations))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SymbolResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SymbolResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SymbolResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SymbolResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto(l, v)
}
func easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto1(in *jlexer.Lexer, out *SymbolBlockListRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]SymbolResult, 0, 0)
					} else {
						out.Result = []SymbolResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 SymbolResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto1(out *jwriter.Writer, in SymbolBlockListRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SymbolBlockListRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SymbolBlockListRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SymbolBlockListRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SymbolBlockListRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto1(l, v)
}
func easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto2(in *jlexer.Lexer, out *SymbolBlockListReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto2(out *jwriter.Writer, in SymbolBlockListReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SymbolBlockListReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SymbolBlockListReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SymbolBlockListReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SymbolBlockListReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto2(l, v)
}
func easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto3(in *jlexer.Lexer, out *GetBlockStatusRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int64(in.Int64())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto3(out *jwriter.Writer, in GetBlockStatusRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetBlockStatusRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetBlockStatusRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetBlockStatusRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetBlockStatusRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto3(l, v)
}
func easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto4(in *jlexer.Lexer, out *GetBlockStatusReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto4(out *jwriter.Writer, in GetBlockStatusReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetBlockStatusReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetBlockStatusReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a804300EncodeGithubComOpenserverOpenStdrpcApiMainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetBlockStatusReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetBlockStatusReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a804300DecodeGithubComOpenserverOpenStdrpcApiMainDto4(l, v)
}
