// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto(in *jlexer.Lexer, out *TxData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "dataSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataSign = string(in.String())
			}
		case "tradeSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradeSign = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.SignerList)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto(out *jwriter.Writer, in TxData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"dataSign\":"
		out.RawString(prefix)
		out.String(string(in.DataSign))
	}
	{
		const prefix string = ",\"tradeSign\":"
		out.RawString(prefix)
		out.String(string(in.TradeSign))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix)
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.SignerList {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto1(in *jlexer.Lexer, out *SubmitRawTransactionRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Txid = string(in.String())
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Wxid = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "from":
			if in.IsNull() {
				in.Skip()
				out.From = nil
			} else {
				in.Delim('[')
				if out.From == nil {
					if !in.IsDelim(']') {
						out.From = make([]string, 0, 4)
					} else {
						out.From = []string{}
					}
				} else {
					out.From = (out.From)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.From = append(out.From, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "to":
			if in.IsNull() {
				in.Skip()
				out.To = nil
			} else {
				in.Delim('[')
				if out.To == nil {
					if !in.IsDelim(']') {
						out.To = make([]string, 0, 4)
					} else {
						out.To = []string{}
					}
				} else {
					out.To = (out.To)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.To = append(out.To, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "decimal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimal = int32(in.Int32())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "isMemo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsMemo = bool(in.Bool())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "received":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Received = bool(in.Bool())
			}
		case "submitTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubmitTime = int64(in.Int64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto1(out *jwriter.Writer, in SubmitRawTransactionRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Txid))
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.Wxid))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		if in.From == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.From {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.To {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"decimal\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimal))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"isMemo\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsMemo))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"received\":"
		out.RawString(prefix)
		out.Bool(bool(in.Received))
	}
	{
		const prefix string = ",\"submitTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubmitTime))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransactionRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransactionRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransactionRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransactionRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto1(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto2(in *jlexer.Lexer, out *SubmitRawTransactionReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txData":
			if in.IsNull() {
				in.Skip()
				out.TxData = nil
			} else {
				if out.TxData == nil {
					out.TxData = new(TxData)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.TxData).UnmarshalEasyJSON(in)
				}
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto2(out *jwriter.Writer, in SubmitRawTransactionReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txData\":"
		out.RawString(prefix[1:])
		if in.TxData == nil {
			out.RawString("null")
		} else {
			(*in.TxData).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransactionReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransactionReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransactionReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransactionReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto2(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto3(in *jlexer.Lexer, out *SubmitRawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "rawHexSig":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHexSig = string(in.String())
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = uint64(in.Uint64())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "sigCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SigCount = int64(in.Int64())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v9 string
					if in.IsNull() {
						in.Skip()
					} else {
						v9 = string(in.String())
					}
					(out.To)[key] = v9
					in.WantComma()
				}
				in.Delim('}')
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "sigParts":
			if in.IsNull() {
				in.Skip()
				out.SigParts = nil
			} else {
				in.Delim('[')
				if out.SigParts == nil {
					if !in.IsDelim(']') {
						out.SigParts = make([]SigParts, 0, 1)
					} else {
						out.SigParts = []SigParts{}
					}
				} else {
					out.SigParts = (out.SigParts)[:0]
				}
				for !in.IsDelim(']') {
					var v10 SigParts
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.SigParts = append(out.SigParts, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "errorMsg":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ErrorMsg = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v11 string
					if in.IsNull() {
						in.Skip()
					} else {
						v11 = string(in.String())
					}
					(out.ErrorMsg)[key] = v11
					in.WantComma()
				}
				in.Delim('}')
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Account).UnmarshalEasyJSON(in)
			}
		case "dataType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataType = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto3(out *jwriter.Writer, in SubmitRawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"rawHexSig\":"
		out.RawString(prefix)
		out.String(string(in.RawHexSig))
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ReqSigs))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"sigCount\":"
		out.RawString(prefix)
		out.Int64(int64(in.SigCount))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.To {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.String(string(v12Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"sigParts\":"
		out.RawString(prefix)
		if in.SigParts == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v13, v14 := range in.SigParts {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"errorMsg\":"
		out.RawString(prefix)
		if in.ErrorMsg == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v15First := true
			for v15Name, v15Value := range in.ErrorMsg {
				if v15First {
					v15First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v15Name))
				out.RawByte(':')
				out.String(string(v15Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		(in.Account).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"dataType\":"
		out.RawString(prefix)
		out.Int64(int64(in.DataType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubmitRawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubmitRawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubmitRawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubmitRawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto3(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto4(in *jlexer.Lexer, out *SmartCoinInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto4(out *jwriter.Writer, in SmartCoinInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartCoinInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartCoinInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartCoinInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartCoinInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto4(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto5(in *jlexer.Lexer, out *SigParts) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Key = string(in.String())
			}
		case "sig":
			if in.IsNull() {
				in.Skip()
				out.Sig = nil
			} else {
				in.Delim('[')
				if out.Sig == nil {
					if !in.IsDelim(']') {
						out.Sig = make([]KeySig, 0, 0)
					} else {
						out.Sig = []KeySig{}
					}
				} else {
					out.Sig = (out.Sig)[:0]
				}
				for !in.IsDelim(']') {
					var v16 KeySig
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Sig = append(out.Sig, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto5(out *jwriter.Writer, in SigParts) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"sig\":"
		out.RawString(prefix)
		if in.Sig == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Sig {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SigParts) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SigParts) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SigParts) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SigParts) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto5(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto6(in *jlexer.Lexer, out *KeySig) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "derivedPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DerivedPath = string(in.String())
			}
		case "eccType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EccType = uint32(in.Uint32())
			}
		case "inputIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.InputIndex = int64(in.Int64())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "signed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signed = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "isImport":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsImport = int64(in.Int64())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "rsv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Rsv = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto6(out *jwriter.Writer, in KeySig) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"derivedPath\":"
		out.RawString(prefix)
		out.String(string(in.DerivedPath))
	}
	{
		const prefix string = ",\"eccType\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.EccType))
	}
	{
		const prefix string = ",\"inputIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.InputIndex))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"signed\":"
		out.RawString(prefix)
		out.String(string(in.Signed))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"isImport\":"
		out.RawString(prefix)
		out.Int64(int64(in.IsImport))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"rsv\":"
		out.RawString(prefix)
		out.Bool(bool(in.Rsv))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KeySig) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KeySig) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KeySig) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KeySig) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto6(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto7(in *jlexer.Lexer, out *GetTransactionFeeEstimatedRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "gasLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GasLimit = string(in.String())
			}
		case "gasPrice":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GasPrice = string(in.String())
			}
		case "fee":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fee = string(in.String())
			}
		case "mainBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainBalance = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto7(out *jwriter.Writer, in GetTransactionFeeEstimatedRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"gasLimit\":"
		out.RawString(prefix[1:])
		out.String(string(in.GasLimit))
	}
	{
		const prefix string = ",\"gasPrice\":"
		out.RawString(prefix)
		out.String(string(in.GasPrice))
	}
	{
		const prefix string = ",\"fee\":"
		out.RawString(prefix)
		out.String(string(in.Fee))
	}
	{
		const prefix string = ",\"mainBalance\":"
		out.RawString(prefix)
		out.String(string(in.MainBalance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionFeeEstimatedRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionFeeEstimatedRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionFeeEstimatedRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionFeeEstimatedRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto7(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto8(in *jlexer.Lexer, out *GetTransactionFeeEstimatedReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = int32(in.Int32())
			}
		case "tokenAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenAddress = string(in.String())
			}
		case "tokenDecimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TokenDecimals = int32(in.Int32())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto8(out *jwriter.Writer, in GetTransactionFeeEstimatedReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimals))
	}
	{
		const prefix string = ",\"tokenAddress\":"
		out.RawString(prefix)
		out.String(string(in.TokenAddress))
	}
	{
		const prefix string = ",\"tokenDecimals\":"
		out.RawString(prefix)
		out.Int32(int32(in.TokenDecimals))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionFeeEstimatedReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionFeeEstimatedReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionFeeEstimatedReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionFeeEstimatedReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto8(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto9(in *jlexer.Lexer, out *GetTransactionCountOnChainRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto9(out *jwriter.Writer, in GetTransactionCountOnChainRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Nonce))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionCountOnChainRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionCountOnChainRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionCountOnChainRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionCountOnChainRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto9(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto10(in *jlexer.Lexer, out *GetTransactionCountOnChainReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto10(out *jwriter.Writer, in GetTransactionCountOnChainReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetTransactionCountOnChainReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetTransactionCountOnChainReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetTransactionCountOnChainReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetTransactionCountOnChainReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto10(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto11(in *jlexer.Lexer, out *FeesSupportAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "fixSupportAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FixSupportAmount = string(in.String())
			}
		case "feesSupportScale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeesSupportScale = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto11(out *jwriter.Writer, in FeesSupportAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"fixSupportAmount\":"
		out.RawString(prefix)
		out.String(string(in.FixSupportAmount))
	}
	{
		const prefix string = ",\"feesSupportScale\":"
		out.RawString(prefix)
		out.String(string(in.FeesSupportScale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeesSupportAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeesSupportAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto11(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto12(in *jlexer.Lexer, out *CreateTradeRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txData":
			if in.IsNull() {
				in.Skip()
				out.TxData = nil
			} else {
				in.Delim('[')
				if out.TxData == nil {
					if !in.IsDelim(']') {
						out.TxData = make([]*TxData, 0, 8)
					} else {
						out.TxData = []*TxData{}
					}
				} else {
					out.TxData = (out.TxData)[:0]
				}
				for !in.IsDelim(']') {
					var v19 *TxData
					if in.IsNull() {
						in.Skip()
						v19 = nil
					} else {
						if v19 == nil {
							v19 = new(TxData)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v19).UnmarshalEasyJSON(in)
						}
					}
					out.TxData = append(out.TxData, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto12(out *jwriter.Writer, in CreateTradeRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txData\":"
		out.RawString(prefix[1:])
		if in.TxData == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.TxData {
				if v20 > 0 {
					out.RawByte(',')
				}
				if v21 == nil {
					out.RawString("null")
				} else {
					(*v21).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTradeRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTradeRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTradeRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTradeRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto12(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto13(in *jlexer.Lexer, out *CreateTradeReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					(out.To)[key] = v22
					in.WantComma()
				}
				in.Delim('}')
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto13(out *jwriter.Writer, in CreateTradeReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v23First := true
			for v23Name, v23Value := range in.To {
				if v23First {
					v23First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v23Name))
				out.RawByte(':')
				out.String(string(v23Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateTradeReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateTradeReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateTradeReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateTradeReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto13(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto14(in *jlexer.Lexer, out *CreateSummaryTxReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "minTransfer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinTransfer = string(in.String())
			}
		case "retainedBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RetainedBalance = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "addressStartIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressStartIndex = int64(in.Int64())
			}
		case "addressLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressLimit = int64(in.Int64())
			}
		case "confirms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirms = int64(in.Int64())
			}
		case "feesSupportAccount":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.FeesSupportAccount).UnmarshalEasyJSON(in)
			}
		case "memo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Memo = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto14(out *jwriter.Writer, in CreateSummaryTxReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"minTransfer\":"
		out.RawString(prefix)
		out.String(string(in.MinTransfer))
	}
	{
		const prefix string = ",\"retainedBalance\":"
		out.RawString(prefix)
		out.String(string(in.RetainedBalance))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"addressStartIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressStartIndex))
	}
	{
		const prefix string = ",\"addressLimit\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressLimit))
	}
	{
		const prefix string = ",\"confirms\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirms))
	}
	{
		const prefix string = ",\"feesSupportAccount\":"
		out.RawString(prefix)
		(in.FeesSupportAccount).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"memo\":"
		out.RawString(prefix)
		out.String(string(in.Memo))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSummaryTxReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSummaryTxReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSummaryTxReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSummaryTxReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto14(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto15(in *jlexer.Lexer, out *CoinInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "contractABI":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractABI = string(in.String())
			}
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Contract).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto15(out *jwriter.Writer, in CoinInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix)
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"contractABI\":"
		out.RawString(prefix)
		out.String(string(in.ContractABI))
	}
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix)
		(in.Contract).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CoinInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CoinInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CoinInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CoinInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto15(l, v)
}
func easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto16(in *jlexer.Lexer, out *AssetsAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "ownerKeys":
			if in.IsNull() {
				in.Skip()
				out.OwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OwnerKeys = make([]string, 0, 4)
					} else {
						out.OwnerKeys = []string{}
					}
				} else {
					out.OwnerKeys = (out.OwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v24 string
					if in.IsNull() {
						in.Skip()
					} else {
						v24 = string(in.String())
					}
					out.OwnerKeys = append(out.OwnerKeys, v24)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		case "mainSymbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MainSymbol = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = int64(in.Int64())
			}
		case "isTrust":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsTrust = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto16(out *jwriter.Writer, in AssetsAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"ownerKeys\":"
		out.RawString(prefix)
		if in.OwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v25, v26 := range in.OwnerKeys {
				if v25 > 0 {
					out.RawByte(',')
				}
				out.String(string(v26))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressIndex))
	}
	{
		const prefix string = ",\"mainSymbol\":"
		out.RawString(prefix)
		out.String(string(in.MainSymbol))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReqSigs))
	}
	{
		const prefix string = ",\"isTrust\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsTrust))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AssetsAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AssetsAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB0fe1dfcEncodeGithubComOpenserverOpenStdrpcApiMainDto16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AssetsAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AssetsAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB0fe1dfcDecodeGithubComOpenserverOpenStdrpcApiMainDto16(l, v)
}
