// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto(in *jlexer.Lexer, out *WalletResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "ctime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Ctime = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto(out *jwriter.Writer, in WalletResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix)
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"ctime\":"
		out.RawString(prefix)
		out.Int64(int64(in.Ctime))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto1(in *jlexer.Lexer, out *FindWalletByWalletIDRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Result).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto1(out *jwriter.Writer, in FindWalletByWalletIDRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		(in.Result).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletByWalletIDRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletByWalletIDRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletByWalletIDRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletByWalletIDRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto1(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto2(in *jlexer.Lexer, out *FindWalletByWalletIDReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto2(out *jwriter.Writer, in FindWalletByWalletIDReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletByWalletIDReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletByWalletIDReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletByWalletIDReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletByWalletIDReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto2(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto3(in *jlexer.Lexer, out *FindWalletByParamsRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]WalletResult, 0, 0)
					} else {
						out.Result = []WalletResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v1 WalletResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Limit).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto3(out *jwriter.Writer, in FindWalletByParamsRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Result {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		(in.Limit).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletByParamsRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletByParamsRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletByParamsRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletByParamsRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto3(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto4(in *jlexer.Lexer, out *FindWalletByParamsReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "sort":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sort = int(in.Int())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto4(out *jwriter.Writer, in FindWalletByParamsReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"sort\":"
		out.RawString(prefix)
		out.Int(int(in.Sort))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletByParamsReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletByParamsReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletByParamsReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletByParamsReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto4(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto5(in *jlexer.Lexer, out *CreateWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Result = bool(in.Bool())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto5(out *jwriter.Writer, in CreateWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Result))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto5(l, v)
}
func easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto6(in *jlexer.Lexer, out *CreateWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "userID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto6(out *jwriter.Writer, in CreateWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"userID\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22b96abEncodeGithubComOpenserverOpenStdrpcApiMainDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22b96abDecodeGithubComOpenserverOpenStdrpcApiMainDto6(l, v)
}
