// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto(in *jlexer.Lexer, out *WalletResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "rootPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootPath = string(in.String())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto(out *jwriter.Writer, in WalletResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"rootPath\":"
		out.RawString(prefix)
		out.String(string(in.RootPath))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int(int(in.Version))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v WalletResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v WalletResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *WalletResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *WalletResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto1(in *jlexer.Lexer, out *UnlockWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto1(out *jwriter.Writer, in UnlockWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UnlockWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UnlockWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UnlockWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UnlockWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto1(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto2(in *jlexer.Lexer, out *UnlockWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "filename":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Filename = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto2(out *jwriter.Writer, in UnlockWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"filename\":"
		out.RawString(prefix[1:])
		out.String(string(in.Filename))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UnlockWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UnlockWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UnlockWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UnlockWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto2(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto3(in *jlexer.Lexer, out *SignTransactionRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					(out.SignerList)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto3(out *jwriter.Writer, in SignTransactionRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix[1:])
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.SignerList {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				out.String(string(v2Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SignTransactionRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SignTransactionRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SignTransactionRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SignTransactionRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto3(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto4(in *jlexer.Lexer, out *FindWalletListRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
				out.Result = nil
			} else {
				in.Delim('[')
				if out.Result == nil {
					if !in.IsDelim(']') {
						out.Result = make([]WalletResult, 0, 1)
					} else {
						out.Result = []WalletResult{}
					}
				} else {
					out.Result = (out.Result)[:0]
				}
				for !in.IsDelim(']') {
					var v3 WalletResult
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					out.Result = append(out.Result, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto4(out *jwriter.Writer, in FindWalletListRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		if in.Result == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v4, v5 := range in.Result {
				if v4 > 0 {
					out.RawByte(',')
				}
				(v5).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletListRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletListRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletListRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletListRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto4(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto5(in *jlexer.Lexer, out *FindWalletListReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto5(out *jwriter.Writer, in FindWalletListReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FindWalletListReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FindWalletListReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FindWalletListReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FindWalletListReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto5(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto6(in *jlexer.Lexer, out *CreateWalletRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto6(out *jwriter.Writer, in CreateWalletRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateWalletRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateWalletRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateWalletRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateWalletRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto6(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto7(in *jlexer.Lexer, out *CreateWalletReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto7(out *jwriter.Writer, in CreateWalletReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix[1:])
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateWalletReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateWalletReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateWalletReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateWalletReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto7(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto8(in *jlexer.Lexer, out *CreateAccountRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "otherOwnerKeys":
			if in.IsNull() {
				in.Skip()
				out.OtherOwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OtherOwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OtherOwnerKeys = make([]string, 0, 4)
					} else {
						out.OtherOwnerKeys = []string{}
					}
				} else {
					out.OtherOwnerKeys = (out.OtherOwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v6 string
					if in.IsNull() {
						in.Skip()
					} else {
						v6 = string(in.String())
					}
					out.OtherOwnerKeys = append(out.OtherOwnerKeys, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReqSigs = int64(in.Int64())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdPath = string(in.String())
			}
		case "accountIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountIndex = int64(in.Int64())
			}
		case "addressIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto8(out *jwriter.Writer, in CreateAccountRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"otherOwnerKeys\":"
		out.RawString(prefix)
		if in.OtherOwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.OtherOwnerKeys {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Int64(int64(in.ReqSigs))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HdPath))
	}
	{
		const prefix string = ",\"accountIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AccountIndex))
	}
	{
		const prefix string = ",\"addressIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAccountRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAccountRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAccountRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAccountRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto8(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto9(in *jlexer.Lexer, out *CreateAccountReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "lastIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastIndex = int64(in.Int64())
			}
		case "curve":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Curve = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto9(out *jwriter.Writer, in CreateAccountReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"lastIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastIndex))
	}
	{
		const prefix string = ",\"curve\":"
		out.RawString(prefix)
		out.Int64(int64(in.Curve))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAccountReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAccountReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAccountReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAccountReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto9(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto10(in *jlexer.Lexer, out *AppLoginRes) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "subject":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Subject = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto10(out *jwriter.Writer, in AppLoginRes) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"subject\":"
		out.RawString(prefix[1:])
		out.String(string(in.Subject))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppLoginRes) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppLoginRes) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppLoginRes) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppLoginRes) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto10(l, v)
}
func easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto11(in *jlexer.Lexer, out *AppLoginReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "appID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "sign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sign = string(in.String())
			}
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = int64(in.Int64())
			}
		case "cmd":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cmd = string(in.String())
			}
		case "prevID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PrevID = int64(in.Int64())
			}
		case "lastID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LastID = int64(in.Int64())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int64(in.Int64())
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int64(in.Int64())
			}
		case "countQ":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CountQ = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto11(out *jwriter.Writer, in AppLoginReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"appID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"sign\":"
		out.RawString(prefix)
		out.String(string(in.Sign))
	}
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Int64(int64(in.Time))
	}
	{
		const prefix string = ",\"cmd\":"
		out.RawString(prefix)
		out.String(string(in.Cmd))
	}
	{
		const prefix string = ",\"prevID\":"
		out.RawString(prefix)
		out.Int64(int64(in.PrevID))
	}
	{
		const prefix string = ",\"lastID\":"
		out.RawString(prefix)
		out.Int64(int64(in.LastID))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int64(int64(in.Offset))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	{
		const prefix string = ",\"countQ\":"
		out.RawString(prefix)
		out.Bool(bool(in.CountQ))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppLoginReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppLoginReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2c14bEncodeGithubComBlocktreeGoOpenwSdkV2WebDto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppLoginReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppLoginReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2c14bDecodeGithubComBlocktreeGoOpenwSdkV2WebDto11(l, v)
}
